[package]
name        = "sheetio"
description = "A Flix library built on top of Apache POI to read and write Excel files."
version     = "0.1.0"
flix        = "0.37.0"
license     = "Apache-2.0"
authors     = ["Stephen Tetley <stephen.tetley@gmail.com>"]

[dependencies]
"github:stephentetley/basis-base"                = "0.4.1"
"github:stephentetley/flix-time"                 = "0.4.0"
"github:stephentetley/graded-lib"                = "0.6.1"
"github:stephentetley/interop-base"              = "0.6.0"


[mvn-dependencies]
# "com.github.virtuald:curvesapi"             = "1.07"
"com.zaxxer:SparseBitSet"                   = "1.2"
"commons-codec:commons-codec"               = "1.15"
"commons-io:commons-io"                     = "2.11.0"
"commons-logging:commons-logging"           = "1.2"
"org.apache.commons:commons-collections4"   = "4.4"
"org.apache.commons:commons-compress"       = "1.23.0"
"org.apache.commons:commons-math3"          = "3.6.1"
"org.apache.logging.log4j:log4j-api"        = "2.20.0"
"org.apache.logging.log4j:log4j-core"       = "2.20.0"
"org.apache.poi:poi"                        = "5.2.3"
"org.apache.poi:poi-ooxml"                  = "5.2.3"
"org.apache.poi:poi-ooxml-full"             = "5.2.3"
"org.apache.xmlbeans:xmlbeans"              = "5.1.1"
"org.slf4j:slf4j-api"                       = "2.0.7"

